### ISSUE TITLE
Password in command line? 2FA auth support?

### ISSUE THREAD

**Issue by crok** [yshalsager/facebook2rss#9]
Hi!

this is not really an issue but a feature request / improvement potencial:
in the [Usage](https://github.com/yshalsager/facebook2rss#usage) section I see that one has to provide the Facebook password in plain text in the command line - which is not okay, it will be saved to the shell history file - probably - if you aren't careful enough, which is kind of okay on your own system but still.. If I were you I would provide a way to ask for the password or at least a way to redirect it from somewhere. And 2FA support is the other thing I would like to mention.
Honestly this project is a very nice idea, though!

**Comment by yshalsager** [comment]
@crok You can store your password in.an.environment variable and use it normally from the command line.

I can make this optional by asking for password if it's not provided, but since login is one time task I didn't implement this.

Regarding 2FA I will implement it soon.

Thanks for your suggestions, I'll reopen this issue till I implement the mentioned features.

**Comment by yshalsager** [comment]
Added in https://github.com/yshalsager/facebook2rss/commit/6bbbad57d9cc6dc8b75d17e47d7808554f0b868f
